/*
 * Copyright 2025-Present Danyil Melnytskyi. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License"). You may not use
 * this file except in compliance with the License. You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * http://www.apache.org/licenses/LICENSE-2.0
 */
#include <boost/algorithm/string.hpp>
#include <boost/property_tree/json_parser.hpp>
#include <boost/property_tree/ptree.hpp>
#include <fstream>
#include <iostream>
#include <map>
#include <filesystem>
#include <string>
#include <vector>

namespace pt = boost::property_tree;

struct MetadataField {
    std::string field_name;
    int network_id;
    std::string type_name;
};

std::string sanitize_name(std::string name) {
    boost::replace_first(name, "minecraft:", "");
    return name;
}

int main(int argc, char* argv[]) {
    if (argc != 7) {
        std::cerr << "Usage: " << argv[0] << " <input_json> <output_header> <type> <type_header> <api_namespace>\n";
        return 1;
    }

    std::string input_file = argv[1];
    std::string output_file = argv[2];
    std::string _type = argv[4];
    std::string type_header = argv[5];
    std::string api_namespace = argv[6];


    std::filesystem::create_directories(std::filesystem::path(output_file).parent_path());

    pt::ptree root;
    try {
        pt::read_json(input_file, root);
    } catch (const pt::json_parser_error& e) {
        std::cerr << "Error parsing JSON file: " << e.what() << std::endl;
        return 1;
    }

    std::ofstream out(output_file);
    if (!out) {
        std::cerr << "Error opening output file: " << output_file << std::endl;
        return 1;
    }

    out << "// Generated by id_proxy_gen tool\n";
    out << "#pragma once\n\n";
    out << "#include \""<<type_header<<"\"\n";


    out << "namespace copper_server::api::"<<api_namespace<<" {\n";

    for (const auto& entity_pair : root) {
        std::string item_name;
        if (entity_pair.first.empty())
            item_name = sanitize_name(entity_pair.second.get<std::string>("named_id"));
        else
            item_name = sanitize_name(entity_pair.first);
        auto id = entity_pair.second.get<int>("id");

        out << "    constexpr " << _type << " " << item_name << "{ " << id << " };\n";
    }

    out << "}\n";

    std::cout << "Successfully generated entity proxies to " << output_file << std::endl;

    return 0;
}
