// Generated by entity_proxy_gen tool
#pragma once

#include <functional>
#include <string_view>
#include <src/generated/entity/wrappers.hpp>
#include <src/api/ecs/base_components.hpp>

namespace copper_server::api::entity_proxy {
    using namespace copper_server::generated::wrapper;
}
